# vim:ft=yaml.ansible code: language=ansible
---
- name: Display system facts that are available to Ansible
  hosts: all

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print env
      ansible.builtin.debug:
        var: ansible_facts['env']
    - name: Print distribution
      ansible.builtin.debug:
        var: ansible_facts['distribution']
