# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/inventory.json
# Example inventory file
local:
  hosts:
    localhost:
      ansible_connection: local

fedora:
  children:
    local:

macos:
  children:
    local:
