id = "ansible"
name = "Ansible Language Server"
version = "0.1.0"
schema_version = 1

description = "Ansible language server support for Zed. For the best experience, please find the recommended settings in the extension project's README."
authors = ["Kartik Vashistha <kartikv.work@gmail.com>"]
repository = "https://github.com/kartikvashistha/zed-ansible"

[language_servers.ansible-language-server]
name = "Ansible Language Server"
language = "Ansible"

[grammars.ansible]
repository = "https://github.com/kartikvashistha/zed-tree-sitter-ansible"
commit = "95243a35141b8e531c90b684f9ba83e91f2e3a40"

# [grammars.yaml]
# commit = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"
# repository = "https://github.com/zed-industries/tree-sitter-yaml"
