id = "ansible"
name = "Ansible Language Server"
version = "0.1.1"
schema_version = 1

description = "Ansible language server support for Zed. For the best experience, please find the recommended settings in the extension project's README."
authors = ["Kartik Vashistha <kartikv.work@gmail.com>"]
repository = "https://github.com/kartikvashistha/zed-ansible"

[language_servers.ansible]
name = "Ansible"
language = "Ansible"

[grammars.yaml]
repository = "https://github.com/zed-industries/tree-sitter-yaml"
commit = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"
