---
# handlers file for setup-fedora
- name: Start Docker Service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# Adding unnecessary blank lines to demo ansible-lint diagnostic messages



# This is in lower case on purpose to demo ansible-lint warnings
- name: start podman service
  ansible.builtin.service:
    name: podman
    state: started
    enabled: true
